# Site settings
baseurl = "https://christineuyemura.com/"
languageCode = "en-us"
title = "Christine Uyemura FX TD/Artist"
theme = "hugo-agency-theme"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Christine Uyemura"
  description = "FX TD / FX Artist working in the VFX industry in Montreal"
  # email = "your@email.com"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "Christine!"
    # Optional logo as brand stored in img/
    logo = "logo.svg"
    reel = "Reel"
    portfolio = "Work"
    about = "About"
    contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "https://www.linkedin.com/in/christineuyemura/"
    #  name = "LinkedIn"
    #  weight = 10

  # Client section
    [params.clients_list]
      enable = true
      # Possibility to center items
      #center = true
      # Optional client title specifying the involvement
      #title = "Used and trusted by"

      # All the clients' logos are stored under 'static/img/logos'.
      # Replace them with your clients's logos.
      # Suggestion: .svg in the size of 280px*80px looks good

      [[params.clients]]
        logo = "wdw.jpg"
        link = "#"
      [[params.clients]]
        logo = "scallop.jpg"
        link = "#"
      [[params.clients]]
        logo = "cru.jpg"
        link = "#"
      [[params.clients]]
        logo = "apex.jpg"
        link = "#"
      [[params.clients]]
        logo = "apex.jpg"
        link = "#"
      [[params.clients]]
        logo = "flag.jpg"
        link = "#"
      [[params.clients]]
        logo = "fat.jpg"
        link = "#"
      [[params.clients]]
        logo = "gsoe.jpg"
        link = "#"
      [[params.clients]]
        logo = "bge.jpg"
        link = "#"
      [[params.clients]]
        logo = "tsp.jpg"
        link = "#"
      [[params.clients]]
        logo = "tnc.jpg"
        link = "#"

  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "FX Artist/TD"
    subtitle = "Hi, I'm Christine!a"
    buttonText = "Checkout My Reel"

  # Reel section
  [params.reel]
  	enable = true
    title = "Reel"
    subtitle = "A compilation of my released work"

  # Portfolio section
  [params.portfolio]
    enable = true
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Work"
    subtitle_0 = "Past Shows"
    subtitle_1 = "Past Projects"

    # Shows subsection
    [params.show_list]
      enable = true
      # Possibility to center items
      #center = true
      # All the show' logos are stored under 'static/img/logos'.

      [[params.shows]]
        logo = "flag.jpg"
      [[params.shows]]
        logo = "fat.jpg"
      [[params.shows]]
        logo = "gsoe.jpg"
      [[params.shows]]
        logo = "bge.jpg"
      [[params.shows]]
        logo = "tsp.jpg"
      [[params.shows]]
        logo = "tnc.jpg"



    [params.portfolio.modal]
      client = "Client"
      date = "Date"
      category = "Category"
      buttonText = "Close project"


    # About section
  [params.about]
    enable = true
    title = "About"
    subtitle = "A brief history of Me, or you can "
    resumetext = " download my resume here."
    resumelink = "img/about/ChristineUyemura_Resume_2019-02-05.pdf"
    resumename = "Christine Uyemura Resume"
    endpoint = "New Adventures!"
    endimage = "img/about/adventures.jpg"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      img = "idtech.jpg"
      date = "The Beginning"
      title = "Smyrna, GA"
      description = "I was born and raised in <strong>Smyrna, GA</strong> just outside of Atlanta. I first fell in love with CG while taking a Maya modeling and animation course at iDTech Camps at Emory University when I was in high school. My first ever Maya model was Iron Man."

    [[params.about.events]]
      img = "penn.gif"
      date = "Engineering School"
      title = "Philadelphia, PA"
      description = "I received my Bachelor's of Science in Engineering for Digital Media Design (Computer Graphics) from the <strong>University of Pennsylvania</strong>, minoring in Consumer Psychology. While in school I had several jobs including iD Tech Maya instructor, Computer Science Teaching Assistant, Graphic Designer, and Web Content Intern at Lucasfilm. "

    [[params.about.events]]
      img = "scad.gif"
      date = "Graduate Art School"
      title = "Atlanta, GA"
      description = "I received my MFA in VFX from the <strong>Savannah College of Art and Design</strong>. As a grad student I also worked as a Designer, Developer and Project Manager for Hughes Media, the VFX Tutor and Houdini Teaching Assistant for SCAD and the Digital Artist Intern for Apple's Marketing & Communications CG department in Sunnyvale, CA."

    [[params.about.events]]
      img = "mpc.gif"
      date = "VFX Industry"
      title = "Montreal, QC"
      description = "After finishing my grad degree I moved to Montreal to work as an FX TD at <strong>MPC</strong>. My first film was <em>The Greatest Showman</em>. After working on <em>The Nutcracker and the Four Realms</em> and <em>Godzilla: King of the Monsters</em> I was promoted to Key FX Artist. Since then I have worked on <em>Dumbo</em>, <em>X-Men: Dark Phoenix</em> and <em>Maleficent: Mistress of Evil</em>."


  # Contact section
  [params.contact]
    enable = true
    title = "Say Hello"
    icon = "fa-envelope"
    subtitle  = "Christine Uyemura | FX Artist/TD"
    contactemail = "christineuyemura@gmail.com"
    contactlinkedin = "https://www.linkedin.com/in/christineuyemura/"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Published under the Apache License 2.0."


    [[params.footer.social]]
      icon = "fa-linkedin"
      link = "https://www.linkedin.com/in/christineuyemura/"
      title = "Christine Uyemura on LinkedIn"

    [[params.footer.social]]
      icon = "fa-vimeo"
      link = "https://vimeo.com/christineuyemura"
      title = "Christine Uyemura on Vimeo"
